import turtle
win=turtle.Screen()
a=turtle.Turtle()
a.forward(100)
a.up()
a.forward(100)
a.pendown()
a.forward(100)
a.shape("turtle")
a.shape("arrow")
a.shape("blank")
a.shape("circle")
a.shape("classic")
a.shape("square")
a.shape("triangle")
a.speed(1)
